<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
        <Authors>Anton Moldovan</Authors>
        <Company>NBomber</Company>
        <Version>6.2.1</Version>
        <Copyright>NBomber@2026</Copyright>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageIcon>nbomber_icon.png</PackageIcon>
        <RepositoryUrl>https://github.com/PragmaticFlow/NBomber.Http</RepositoryUrl>
        <PackageTags>load-testing, performance-testing, integration-testing, fsharp</PackageTags>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <Description>NBomber plugin for defining HTTP scenarios</Description>
        <Title>NBomber.Http</Title>
        <OtherFlags>$(OtherFlags) --test:GraphBasedChecking --test:ParallelOptimization --test:ParallelIlxGen</OtherFlags>
    </PropertyGroup>

    <PropertyGroup>
        <NuGetAudit>true</NuGetAudit>
        <NuGetAuditMode>all</NuGetAuditMode>
        <NuGetAuditLevel>low</NuGetAuditLevel>
        <WarningsAsErrors>NU1900;NU1901;NU1902;NU1903;NU1904</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Constants.fs" />
        <Compile Include="HttpMetricsPlugin.fs" />
        <Compile Include="FSharp.fs" />
        <Compile Include="CSharp.fs" />
    </ItemGroup>

    <ItemGroup>
        <None Include="../../LICENSE" Pack="true" Visible="false" PackagePath="" />
        <None Include="../../assets/nbomber_icon.png" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NBomber.Contracts" Version="6.3.0" />        
    </ItemGroup>

</Project>
