<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ServerGarbageCollection>false</ServerGarbageCollection>
        <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="SequentialSteps.fs" />
        <Compile Include="SimpleExample.fs" />
        <Compile Include="Program.fs" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Update="FSharp.Core" Version="9.0.300" />
        <PackageReference Include="NBomber" Version="6.1.0-beta.19" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\NBomber.Http\NBomber.Http.fsproj" />
    </ItemGroup>

</Project>
